### ISSUE TITLE
The figures do not show up!

### ISSUE THREAD

**Issue by chengjun** [ar0ne/latex-equation-editor#1]
I tried to launch the app on github's gh-pages branch, check this link https://chengjun.github.io/latex/index.html, but the figures do not show. Any solutions? Many thanks.

**Comment by ar0ne** [comment]
Hi, chengjun
It's impossible to use github gh-pages to run this application. Because we need server (Apache Http Server, Python CGI Http Server, etc), we need something that can process CGI.

**Comment by chengjun** [comment]
Thank you for your reply.
